### ISSUE TITLE
How does this compare to CodeFormer?

### ISSUE THREAD

**Issue by CamiloMM** [wzhouxiff/RestoreFormer#12]
For a moment and due to the similar names I assumed this was related to [CodeFormer](https://shangchenzhou.com/projects/CodeFormer/) but it seems it's just a coincidence, the researchers are different and from different institution entirely.

However I might be wrong, since both papers were released only 3 days apart? Either way, it'd be nice to have a comparison of both, especially if you beat them in quality.

**Comment by CamiloMM** [comment]
Well, tried it myself, by being extremely lazy and using some extra tools meant for Stable Diffusion so take it with a grain of salt
![figure1](https://user-images.githubusercontent.com/2404138/191048148-ffc6c25f-12ca-464f-a464-758746902c0d.png)

Either way RestoreFormer seems to do something magical with the hair.

**Comment by wzhouxiff** [comment]
If you trace the published time detailly, you will find that CodeFormer is released later than ours about 3 months.

**Comment by CamiloMM** [comment]
You're right, I checked the date on the paper but I should have compared the date of the github repos.
