### ISSUE TITLE
Can I train RestoreFormer on 1024x1024?

### ISSUE THREAD

**Issue by luser350** [wzhouxiff/RestoreFormer#28]
Hi, I want to train a model on 1k resolution. Since it is mentioned in the readme that FFHQ images were resized to 512x512. Does your model support 1K resolution training and generating 1K resolution images?

**Comment by luser350** [comment]
@wzhouxiff can you please answer?

**Comment by wzhouxiff** [comment]
Yes, you can finetune the model of our RestoreFormer/ [RestoreFormer++](https://github.com/wzhouxiff/RestoreFormerPlusPlus) on 1k resolution. However, we suggest adapting the HQ_Dictionary to 1k resolution first before restoration.
