### ISSUE TITLE
Training with own data

### ISSUE THREAD

**Issue by AugustLee93** [wzhouxiff/RestoreFormer#4]
Hi there, 
Could you provide the training script if I would like to train on my own dataset? 
The architecture of data folder is like:
--mydata
------train
------------A(haze one)
------------B(Groundtruth)
-------test
------------A(haze one)
------------B(Groundtruth)

**Comment by wzhouxiff** [comment]
Our method is trained with synthetic images and the degraded face images is on-line synthesized from high-quality face images with degrading model. Therefore, while training, we only take high-quality images as input. 
If you want to replace the high-quality images with you own dataset, what you should do is to add your folder path to dataroot_gt in the configure file.
If you want to read the degraded image and gt simultaneously, you need to rewrite the dataloader.
