### ISSUE TITLE
请问在哪里可以下载supplemental materials

### ISSUE THREAD

**Issue by zhoumenghan** [wzhouxiff/RestoreFormer#7]
您好，请问在哪里可以下载supplemental materials，谢谢~

**Comment by wzhouxiff** [comment]
https://openaccess.thecvf.com/content/CVPR2022/supplemental/Wang_RestoreFormer_High-Quality_Blind_CVPR_2022_supplemental.pdf

**Comment by zhoumenghan** [comment]
谢谢呀

**Comment by zhoumenghan** [comment]
您好，还有一个问题，我看到您论文里用到的测试数据集和GFPGAN一致，都是LFW-Test, CelebChild-Test, WebPhoto, and CelebA-Test. 请问这些数据集可以分享出来吗？有没有下载链接呢谢谢

**Comment by wzhouxiff** [comment]
LFW: http://vis-www.cs.umass.edu/lfw/#views. Select out the first image of each identity in the validation set.
WebPhoto and CelebA-Test: https://xinntao.github.io/projects/gfpgan
CelebA-Test: https://github.com/suvojit-0x55aa/celebA-HQ-dataset-download

**Comment by huilicici** [comment]
您好，请问如何得到3000 CelebA-Test data? 或者哪里有partition file for CelebA-HQ-dataset?

**Comment by wzhouxiff** [comment]
We upload the CelebA-Test data to [BaiduYun](https://pan.baidu.com/s/1iUvBBFMkjgPcWrhZlZY2og?pwd=test)
