### ISSUE TITLE
Question about vector quantization

### ISSUE THREAD

**Issue by IDKiro** [wzhouxiff/RestoreFormer#8]
I genuinely think it is a good idea. 

Since I have no research experience in vector quantization, I would like to know how to ensure that all tokens in the Dict are optimized. If there is a token in the Dict that is far away from the image's all feature tokens, then it may not be selected by argmin during training.

**Comment by wzhouxiff** [comment]
In our implemention, we do nothing to force all the tokens to be optimized while training, but we used to calculate the utilization rate of the tokens and it reached about 99%.

If you want to optimized all the tokens, more implementations are [here](https://github.com/CompVis/taming-transformers/blob/master/taming/modules/vqvae/quantize.py )

**Comment by IDKiro** [comment]
It addresses my concern.
Thanks!
