### ISSUE TITLE
About FID on test datasets

### ISSUE THREAD

**Issue by hhuyujie** [wzhouxiff/RestoreFormer#9]
The real HR images need to be input when calculating FID. Is the real HR images from FFHQ or GT corresponding to CelebA-HQ when testing on the CelebA-test dataset? When testing on real-world datasets without GT, is FFHQ used?

**Comment by wzhouxiff** [comment]
All the datasets, including the synthetic dataset and real-world datasets, are measured on the same pre-calculated FFHQ inception feature statistics:
[inception_FFHQ_512-f7b384ab.pth](https://gitcode.net/mirrors/xinntao/basicsr/-/blob/master/docs/Metrics.md)
